export enum ActionType {
  AUTH_START = "AUTH_START",
  AUTH_SUCCESS = "AUTH_SUCCESS",
  AUTH_FAIL = "AUTH_FAIL",
  AUTH_LOGOUT = "AUTH_LOGOUT",
  FETCH_SERVERS_START = "FETCH_SERVERS_START",
  FETCH_SERVERS_SUCCESS = "FETCH_SERVERS_SUCCESS",
  FETCH_SERVERS_FAIL = "FETCH_SERVERS_FAIL",
  SORT_SERVERS_BY_NAME = "SORT_SERVERS_BY_NAME",
  SORT_SERVERS_BY_DISTANCE = "SORT_SERVERS_BY_DISTANCE",
}
